import { InterestsData } from "./components/table/columns";

export const interestsData: InterestsData[] = [
    {
        firstName: "محمد",
        surName: "الزهراني",
        phone: "0551234567",
        email: "mohammed.zahrani@example.com",
        region: "المركز",
        buildingNumber: 101,
        buildingStatus: "متاح",
    },
    {
        firstName: "فاطمة",
        surName: "الأنصاري",
        phone: "0569876543",
        email: "fatima.ansari@example.com",
        region: "الشرقي",
        buildingNumber: 202,
        buildingStatus: "محجوز",
    },
    {
        firstName: "علي",
        surName: "الغامدي",
        phone: "0547654321",
        email: "ali.ghamdi@example.com",
        region: "الغربي",
        buildingNumber: 303,
        buildingStatus: "مباع",
    },
    {
        firstName: "نور",
        surName: "الشريف",
        phone: "0538765432",
        email: "noor.shareef@example.com",
        region: "المركز",
        buildingNumber: 404,
        buildingStatus: "متاح",
    },
    {
        firstName: "سارة",
        surName: "العتيبي",
        phone: "0581239876",
        email: "sarah.otaibi@example.com",
        region: "الشرقي",
        buildingNumber: 505,
        buildingStatus: "مباع",
    },
    {
        firstName: "أحمد",
        surName: "الخطيب",
        phone: "0523456789",
        email: "ahmed.khateeb@example.com",
        region: "الغربي",
        buildingNumber: 606,
        buildingStatus: "محجوز",
    },
    {
        firstName: "لمياء",
        surName: "الحربي",
        phone: "0572345678",
        email: "lamya.harbi@example.com",
        region: "المركز",
        buildingNumber: 707,
        buildingStatus: "متاح",
    },
    {
        firstName: "خالد",
        surName: "المطيري",
        phone: "0598765432",
        email: "khaled.mutairi@example.com",
        region: "الشرقي",
        buildingNumber: 808,
        buildingStatus: "مباع",
    },
    {
        firstName: "سارة",
        surName: "العتيبي",
        phone: "0581239876",
        email: "sarah.otaibi@example.com",
        region: "الشرقي",
        buildingNumber: 505,
        buildingStatus: "مباع",
    },
    {
        firstName: "أحمد",
        surName: "الخطيب",
        phone: "0523456789",
        email: "ahmed.khateeb@example.com",
        region: "الغربي",
        buildingNumber: 606,
        buildingStatus: "محجوز",
    },
    {
        firstName: "لمياء",
        surName: "الحربي",
        phone: "0572345678",
        email: "lamya.harbi@example.com",
        region: "المركز",
        buildingNumber: 707,
        buildingStatus: "متاح",
    },
    {
        firstName: "خالد",
        surName: "المطيري",
        phone: "0598765432",
        email: "khaled.mutairi@example.com",
        region: "الشرقي",
        buildingNumber: 808,
        buildingStatus: "مباع",
    },
];